# Generated by Django 3.2.7 on 2021-09-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_teamtask_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamtask',
            name='assigned_to',
        ),
    ]
